### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by Hhhhhhao** [hjbahng/visual_prompting#1]
Thanks for the interesting work.

I'm wondering can you provide the detailed hyper-parameters for each dataset? 
Currently I'm not able to re-produce the results in paper for CIFAR100 using the default parameters.

Thanks in advance for your support.

**Comment by hjbahng** [comment]
I've used the default hyperparameters for every dataset. Which pre-trained model are you using?

**Comment by Hhhhhhao** [comment]
Sorry my fault, I thought the CLIP results in the paper is for RN50 since other vision comparisons are with RN50.
The default backbone should be VIT-B/32 right?
My another question is do you use the default parameters for FT and LP of CLIP too?

**Comment by hjbahng** [comment]
Yes, the default backbone is ViT-B/32, but you can get better results using ViT-B/16.

For LP, I used the official code and hyperparameters released in CLIP ([​Linear-probe evaluation](https://github.com/openai/CLIP#linear-probe-evaluation) using scikit-learn).
For FT, I used the default settings [here](https://github.com/mlfoundations/open_clip).

**Comment by Hhhhhhao** [comment]
Thanks a lot the detailed instructions!

**Comment by alvitawa** [comment]
@hjbahng Just to verify, these are the hyperparameters you used for FT? https://github.com/mlfoundations/open_clip/blob/adbf326abbabd361d8563da375e49a8e4b281d38/src/training/params.py

And did you use the same FT hyperparameters for every dataset (32 epochs for instance)?
