### ISSUE TITLE
Hyperparameters for vision models

### ISSUE THREAD

**Issue by zqypku** [hjbahng/visual_prompting#2]
Hi, thanks for your work and well-organized code!

I am trying to reproduce your experimental results.
However, I could not achieve comparable results when I use visual models as the backbone.
I'm wondering if you could provide the detailed hyper-parameters for each dataset for Instagram, BiT-M, and RN50?

Thanks in advance for your support.

**Comment by Waybaba** [comment]
same question

**Comment by Waybaba** [comment]
> Hi, thanks for your work and well-organized code!
> 
> I am trying to reproduce your experimental results. However, I could not achieve comparable results when I use visual models as the backbone. I'm wondering if you could provide the detailed hyper-parameters for each dataset for Instagram, BiT-M, and RN50?
> 
> Thanks in advance for your support.

Hi, did you find any solutions? Thanks in advance!

**Comment by zqypku** [comment]
Yes, it seems that the pre-trained model (BiT-M) they provide is wrong. I re-download the pre-trained model from the official repository (timm) and get comparable results.
And I set the hyper-parameters following their paper, i.e., lr=40 with 1000 epochs.

**Comment by Waybaba** [comment]
> 

Sounds good. I also re-implemented with the timm model (BiT-M and Instagram) and the Linear Probing result is close to the one in the Table 4 in the paper. While the result of Resnet50 is always much lower than expected.

**Comment by Waybaba** [comment]
> Yes, it seems that the pre-trained model (BiT-M) they provide is wrong. I re-download the pre-trained model from the official repository (timm) and get comparable results. And I set the hyper-parameters following their paper, i.e., lr=40 with 1000 epochs.

Thanks!

**Comment by BalasubramanyamEvani** [comment]
@Waybaba, @zqypku can anyone of you provide the changes you made?
